# Generated by Django 4.2.7 on 2025-08-01 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('databases', '0001_initial'),
        ('pages', '0001_initial'),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='page',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='database', to='pages.page'),
        ),
        migrations.AddField(
            model_name='database',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='databases', to='workspaces.workspace'),
        ),
        migrations.AlterUniqueTogether(
            name='databaserelation',
            unique_together={('from_database', 'to_database', 'from_field')},
        ),
        migrations.AlterUniqueTogether(
            name='databasefield',
            unique_together={('database', 'order')},
        ),
    ]
